### ISSUE TITLE
Instant.withMillis is confusing

### ISSUE THREAD

**Issue by rumpeltux** [JodaOrg/jodaorg.github.io#5]
I was looking for a way to truncate millisecond precision from an Instant, e.g.

    Instant.now().withMillis(0)

But apparently that doesn’t do what I thought and instead creates a new Instant(0).
Maybe the docs can be clarified that this affects the whole timestamp and not only the millisecond precision.

**Comment by jodastephen** [comment]
https://github.com/JodaOrg/joda-time/commit/1e7b4b694926cef7339e265bc2b3fad3b2370367
