### ISSUE TITLE
Convert to com.google.api.client.util.DateTime

### ISSUE THREAD

**Issue by DarrylJohnson170** [JodaOrg/jodaorg.github.io#6]
Is it possible to include a conversion method?  Your DateTime class is amazing and I use it to simplify working with Google's Calendar API. It would be great if you could include a conversion method to com.google.api.client.util.DateTime since having both classes imported can make things confusing and ugly. Thank you!

**Comment by jodastephen** [comment]
While I understand the problem is annoying, I can't add a dependency to Joda-Time for this.
