### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by tripleo1** [JodaOrg/jodaorg.github.io#8]
Is the site open source? Where are the .adoc, etc files?

**Comment by jodastephen** [comment]
The website is generated from each of the separate projects - Joda-Time generates the /joda-time folder and so on. It is done via maven's [site tooling](https://maven.apache.org/plugins/maven-site-plugin/).

**Comment by tripleo1** [comment]
I see that now, thank you.  But when I do:

$ git clone .../joda-time
$ mvn site

I get 

![joda 2020-12-24 22-51-59](https://user-images.githubusercontent.com/50311859/103118550-61a3b480-463d-11eb-8372-4c61e54590ed.png)

**Comment by tripleo1** [comment]
Ok. It doesn't work locally (and I think that's my issue), but it works if I put it in joda-time in my apache root.
Why wouldn't it work locally?

**Comment by jodastephen** [comment]
IIRC, a combination of relative hyperlinks and HTTS support means you get an odd result when you look locally,
